version: '3'
services:
  # postgres数据库
  postgres:
    image: 'postgres:10.5'
  # redis数据库
  redis:
    image: 'redis:4-alpine'
  # nginx
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - '3030:80'
  # api
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/app/node_modules
      - ./server:/usr/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  web:
    build: 
      context: ./web
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/app/node_modules
      - ./web:/usr/app
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/app/node_modules
      - ./worker:/usr/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379