# 使用的的 docker compose 文件标准
version: '3'
# 服务列表，一个容器可以理解为一个服务
services:
  # 容器1
  redis-server:
    # 使用的镜像
    image: redis
  # 容器2
  node-app:
    # 程序永远会在停止时自动重启
    restart: always
    # 构建当前项目
    build: .
    # 端口映射
    ports:
      - 8080:8080
    # 环境变量
    environment:
      - REDIS_URL=redis://redis-server # redis-server是容器1